apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  casdoor-client-secret: {{ .Values.providers.casdoor.clientSecret | b64enc | quote }}
  sync-star-personal-token: {{ .Values.syncStar.personalToken | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  aes-key: {{ .Values.encrypt.aesKey | b64enc | quote }}
  sms-sercret: {{ .Values.sms.clientSecret | b64enc | quote }}